define([], function () {
  return {
    "PropertyPaneDescription": "Infinite possibilities - Configure tabs to organize web parts from anywhere on the page.",
    "BasicGroupName": "Troubleshooting",
    "DescriptionFieldLabel": "Description Field",
    "SectionClass": "Section Selector",
    "WebPartClass": "Web Part Selector",
    "TabLabels": "Tab Labels",
    "ManageTabLabels": "Manage Tab Labels",
    "AppTitle": "PiCanvas",
    "OriginalAuthor": "Originally created by Mark Rackley",
    "UpgradedBy": "Upgraded by @anthonyrhopkins",

    // Template strings
    "TemplatesGroupName": "Templates",
    "TemplatesDescription": "Apply pre-built templates or export/import your configuration",
    "ApplyTemplateLabel": "Apply Template",
    "SelectTemplatePlaceholder": "-- Select a template --",
    "BuiltInTemplatesHeader": "--- Built-in Templates ---",
    "SavedTemplatesHeader": "--- Saved Templates ---",
    "ApplyTemplateButton": "Apply Selected Template",
    "ExportImportHeader": "Export / Import",
    "ExportConfigLabel": "Export Configuration",
    "ImportConfigLabel": "Import Configuration",
    "SaveAsTemplateLabel": "Save as Template",
    "TemplateNamePrompt": "Enter a name for this template:",
    "ExportSuccessMessage": "Configuration exported successfully!",
    "ImportSuccessMessage": "Configuration imported successfully! Please assign web parts to tabs.",
    "SaveTemplateSuccessMessage": "Template saved to Site Assets!",
    "ImportErrorMessage": "Failed to import configuration. Please check the file format.",
    "SaveTemplateErrorMessage": "Failed to save template. Please check your permissions.",
    "NoSiteAssetsAccess": "Site Assets not accessible. Saving templates to SharePoint is disabled, but you can still use Export/Import.",

    // Permission strings
    "PermissionHeaderLabel": "Permissions",
    "PermissionEnabledLabel": "Restrict by Group",
    "PermissionGroupsLabel": "Visible to Groups",
    "PermissionGroupsDescription": "Select which groups can see this tab",
    "PermissionCustomGroupsLabel": "Custom Group IDs",
    "PermissionCustomGroupsPlaceholder": "e.g. 5, 12, 23",
    "PermissionCustomGroupsDescription": "Enter SharePoint group IDs (comma-separated)",
    "PermissionVisibleToAll": "Everyone (no restriction)",
    "PermissionOwnersLabel": "Site Owners",
    "PermissionMembersLabel": "Site Members",
    "PermissionVisitorsLabel": "Site Visitors",
    "PermissionOwnersMembers": "Owners & Members",
    "PermissionMembersVisitors": "Members & Visitors",
    "PermissionAllGroups": "All Site Groups",

    // Permission placeholder strings
    "PermissionPlaceholderLabel": "Show Placeholder",
    "PermissionPlaceholderDescription": "Show disabled tab with message instead of hiding",
    "PermissionPlaceholderTextLabel": "Placeholder Message",
    "PermissionPlaceholderTextPlaceholder": "e.g. Access restricted",
    "PermissionPlaceholderDefault": "Restricted",

    // Lock strings
    "LockHeaderLabel": "Password Lock",
    "LockEnabledLabel": "Require Password",
    "LockEnabledOnText": "Locked",
    "LockEnabledOffText": "Unlocked",
    "LockPasswordSetLabel": "Password is set for this tab.",
    "LockPasswordMissingLabel": "No password set. This tab will stay locked until you set one.",
    "LockPasswordLabel": "Set or Update Password",
    "LockPasswordDescription": "Stored as a one-way hash in web part properties. This is a client-side lock.",
    "LockTemplateToggleLabel": "Customize Lock Screen HTML",
    "LockTemplateToggleOnText": "Custom",
    "LockTemplateToggleOffText": "Default",
    "LockTemplateLabel": "Lock Screen HTML",
    "LockTemplateDescription": "Include data-picanvas-lock-input, data-picanvas-lock-submit, data-picanvas-lock-message. Tokens: {{tabLabel}}, {{tabIndex}}, {{lockTitle}}, {{passwordLabel}}, {{unlockLabel}}.",
    "LockMessagesToggleLabel": "Customize Lock Messages",
    "LockMessagesToggleOnText": "Custom",
    "LockMessagesToggleOffText": "Default",
    "LockPromptMessageLabel": "Prompt Message (HTML)",
    "LockPromptMessageDescription": "Shown before the password is entered.",
    "LockErrorMessageLabel": "Error Message (HTML)",
    "LockErrorMessageDescription": "Shown after an incorrect password.",
    "LockMissingPasswordMessageLabel": "No Password Message (HTML)",
    "LockMissingPasswordMessageDescription": "Shown when no password is configured.",
    "LockSuccessMessageLabel": "Success Message (HTML)",
    "LockSuccessMessageDescription": "Shown briefly after unlocking.",
    "LockPromptMessage": "Enter the password to unlock this tab.",
    "LockErrorMessage": "Incorrect password. Please try again.",
    "LockMissingPasswordMessage": "No password has been set for this tab.",
    "LockSuccessMessage": "Unlocked.",
    "LockTitleText": "Protected content",
    "LockPasswordFieldLabel": "Password",
    "LockUnlockButtonLabel": "Unlock",

    // Lock default strings
    "LockDefaultsGroupName": "Lock Defaults",
    "LockDefaultsDescription": "Set default lock screen HTML and messages for all tabs. Tab-level overrides take precedence.",
    "LockUnlockTtlLabel": "Unlock Duration (minutes)",
    "LockUnlockTtlDescription": "How long an unlocked tab stays open in the current session (1-1440).",
    "LockDefaultTemplateToggleLabel": "Default Lock Screen HTML",
    "LockDefaultTemplateToggleOnText": "Custom",
    "LockDefaultTemplateToggleOffText": "Default",
    "LockDefaultTemplateLabel": "Default Lock Screen HTML",
    "LockDefaultTemplateDescription": "Must include data-picanvas-lock-input, data-picanvas-lock-submit, data-picanvas-lock-message. Tokens: {{tabLabel}}, {{tabIndex}}, {{lockTitle}}, {{passwordLabel}}, {{unlockLabel}}.",
    "LockDefaultMessagesToggleLabel": "Default Lock Messages",
    "LockDefaultMessagesToggleOnText": "Custom",
    "LockDefaultMessagesToggleOffText": "Default",
    "LockDefaultPromptMessageLabel": "Default Prompt Message (HTML)",
    "LockDefaultPromptMessageDescription": "Shown before the password is entered.",
    "LockDefaultErrorMessageLabel": "Default Error Message (HTML)",
    "LockDefaultErrorMessageDescription": "Shown after an incorrect password.",
    "LockDefaultMissingMessageLabel": "Default No Password Message (HTML)",
    "LockDefaultMissingMessageDescription": "Shown when no password is configured.",
    "LockDefaultSuccessMessageLabel": "Default Success Message (HTML)",
    "LockDefaultSuccessMessageDescription": "Shown briefly after unlocking.",

    // Content type strings (v3.0)
    "ContentTypeLabel": "Content Type",
    "ContentTypeWebPart": "SharePoint Web Part",
    "ContentTypeSection": "SharePoint Section",
    "ContentTypeMarkdown": "Markdown Content",
    "ContentTypeHtml": "HTML Content",
    "ContentTypeMermaid": "Mermaid Diagram",
    "ContentTypeEmbed": "Embed (iframe)",
    "ContentTypeJavaScript": "JavaScript Code",

    // Custom content strings (v3.0)
    "CustomContentLabel": "Content",
    "MarkdownPlaceholder": "Enter Markdown content...\n\n# Heading\n**Bold** and *italic* text\n- List item",
    "HtmlPlaceholder": "Enter HTML content...\n\n<div class=\"my-content\">\n  <h2>Title</h2>\n  <p>Your content here</p>\n</div>",
    "MermaidPlaceholder": "Enter Mermaid diagram code...\n\ngraph TD\n    A[Start] --> B{Decision}\n    B -->|Yes| C[Action]\n    B -->|No| D[End]",
    "JavaScriptPlaceholder": "// Simple test - this WILL work!\ncontainer.innerHTML = '<h1 style=\"color: #ec4899; padding: 20px;\">Hello from JavaScript!</h1>';\n\n// Or use render():\n// render('<div style=\"padding: 20px; background: #1e293b; color: white;\"><h2>It works!</h2></div>');\n\n// Or create elements:\n// var btn = create('button', { style: { padding: '10px 20px' }, onclick: function() { alert('Hi!'); } }, 'Click Me');\n// container.appendChild(btn);",
    "JavaScriptFullScreenLabel": "Display Mode",
    "JavaScriptFullScreenOn": "Full Screen",
    "JavaScriptFullScreenOff": "Contained",

    // Embed strings (v3.0)
    "EmbedUrlLabel": "Embed URL",
    "EmbedUrlDescription": "Enter a URL from a trusted domain (YouTube, Power BI, Forms, etc.)",
    "EmbedHeightLabel": "Embed Height",
    "EmbedHeightPlaceholder": "e.g. 400px, 50vh",
    "EmbedFullPageLabel": "Embed Layout",
    "EmbedFullPageOn": "Full Page",
    "EmbedFullPageOff": "Custom",
    "EmbedFullWidthLabel": "Embed Width",
    "EmbedFullWidthOn": "Full Width (edge-to-edge)",
    "EmbedFullWidthOff": "Contained",
    "EmbedFullHeightLabel": "Embed Height Mode",
    "EmbedFullHeightOn": "Full Height (100vh)",
    "EmbedFullHeightOff": "Custom Height",

    // External file strings (v3.1)
    "ContentTypeFile": "External File",
    "FileUrlLabel": "File URL",
    "FileUrlPlaceholder": "/sites/yoursite/SiteAssets/PiCanvas/content.html",
    "FileUrlDescription": "Server-relative path to .html or .md file",
    "BrowseSiteAssetsLabel": "Browse Site Assets",
    "FileLoadingMessage": "Loading content...",
    "FileUrlMissingMessage": "No file URL specified",
    "FileTypeUnsupportedMessage": "Unsupported file type. Use .html or .md files.",
    "FileSourceWebPartMissingMessage": "No Text WebPart selected. Please select a Text WebPart in the settings.",
    "FileSourceWebPartEmptyMessage": "The selected Text WebPart is empty or could not be read.",

    // Content source strings (v3.1)
    "ContentSourceTypeLabel": "Content Source",
    "ContentSourceManual": "Manual Input",
    "ContentSourceWebPart": "Text WebPart on Page",
    "ContentSourceWebPartLabel": "Select Text WebPart",
    "ContentSourceWebPartInfo": "The selected Text WebPart will be hidden and its content rendered here.",

    // Content full-width strings (v3.4)
    "ContentFullWidthLabel": "Content Width",
    "ContentFullWidthOn": "Full Width (edge-to-edge)",
    "ContentFullWidthOff": "Contained",

    // RSS Feed strings (v3.2)
    "ContentTypeRss": "RSS Feed",
    "RssFeedUrlLabel": "Feed URL",
    "RssLayoutLabel": "Layout",
    "RssMaxItemsLabel": "Max Items",
    "RssShowDateLabel": "Show Date",
    "RssShowDescriptionLabel": "Show Description",
    "RssShowImageLabel": "Show Image",
    "RssShowAuthorLabel": "Show Author",
    "RssDescriptionLimitLabel": "Description Length",
    "RssDateFormatLabel": "Date Format",
    "RssLinkTargetLabel": "Open Links In",
    "RssLoadingMessageLabel": "Loading Message",

    // Feature toggle strings (v3.0)
    "EnableDeepLinkingLabel": "Enable URL Deep Linking",
    "EnableDeepLinkingDescription": "Allow linking directly to tabs via URL hash (e.g. #tab-name)",
    "EnableLazyLoadingLabel": "Enable Lazy Loading",
    "EnableLazyLoadingDescription": "Delay loading tab content until tab is activated",

    // Accessibility strings (v3.0)
    "TabListAriaLabel": "Content sections",

    // Metadata Token strings (v3.3)
    "MetadataTokensGroupName": "Page Metadata Tokens",
    "MetadataTokensDescription": "Insert page metadata values into your content using tokens",
    "MetadataTokenPickerLabel": "Available Tokens",
    "MetadataTokenPickerDescription": "Click a token to copy it to clipboard, then paste into your content",
    "MetadataTokenSearchPlaceholder": "Search tokens...",
    "MetadataTokenLoadingMessage": "Loading page metadata...",
    "MetadataTokenErrorMessage": "Could not load page metadata",
    "MetadataTokenCopiedMessage": "Token copied to clipboard",
    "MetadataTokenNoValueText": "No value",
    "MetadataTokenHelpText": "Use {{TokenPath}} syntax in your HTML or Markdown content. Example: {{Title}} or {{Author.Title}}",
    "MetadataTokenCategoryPage": "Page",
    "MetadataTokenCategoryPeople": "People",
    "MetadataTokenCategoryDates": "Dates",
    "MetadataTokenCategorySite": "Site",
    "MetadataTokenCategoryCustom": "Custom Fields",

    // JavaScript Template strings (v3.5)
    "JavaScriptTemplateLabel": "Template",
    "JavaScriptTemplateNone": "— None (Custom Code) —",
    "JavaScriptTemplateDescription": "Select a built-in template or write custom code",
    "JavaScriptTemplateConfigHeader": "Template Configuration",
    "JavaScriptTemplateLandingPage": "Landing Page",
    "JavaScriptTemplateStatsDashboard": "Stats Dashboard",
    "JavaScriptTemplateTimeline": "Timeline",
    "JavaScriptTemplateCardGrid": "Card Grid",
    "JavaScriptTemplateHeroSection": "Hero Section",

    // Table of Contents strings (v3.6)
    "ContentTypeToc": "Table of Contents",
    "ContentTypeProfileReport": "Profile Report",
    "TocInfoText": "Scans the SharePoint page for headings and generates a navigable table of contents.",
    "TocSearchTextLabel": "Scan Text Web Parts",
    "TocSearchMarkdownLabel": "Scan Markdown Web Parts",
    "TocSearchCollapsibleLabel": "Scan Collapsible Sections",
    "TocShowHeading1Label": "Show H2 Headings",
    "TocShowHeading2Label": "Show H3 Headings",
    "TocShowHeading3Label": "Show H4 Headings",
    "TocShowHeading4Label": "Show H5 Headings",
    "TocListStyleLabel": "List Style",
    "TocStickyModeLabel": "Sticky Mode",
    "TocHideInMobileLabel": "Hide on Mobile",
    "TocHideTitleLabel": "Hide Title",
    "TocTitleTextLabel": "TOC Title",
    "TocShowPreviousPageLinkLabel": "Show Back Link",
    "TocPreviousPageTextLabel": "Back Link Text",
    "TocEnabledLabel": "Auto Table of Contents",
    "TocMinHeadingsLabel": "Minimum Headings",
    "TocMaxLevelLabel": "Max Heading Depth",

    // TOC Styling strings (v3.8)
    "TocStylePresetLabel": "Style Preset",
    "TocFontFamilyLabel": "Font Family",
    "TocBaseFontSizeLabel": "Base Font Size",
    "TocTitleFontSizeLabel": "Title Font Size",
    "TocLevelSizeStepLabel": "Level Size Step",
    "TocTitleFontWeightLabel": "Title Font Weight",
    "TocH2FontWeightLabel": "H2 Font Weight",
    "TocSubHeadingFontWeightLabel": "Sub-heading Font Weight",
    "TocLineHeightLabel": "Line Height",
    "TocLetterSpacingLabel": "Letter Spacing",
    "TocLinkColorLabel": "Link Color",
    "TocLinkHoverColorLabel": "Link Hover Color",
    "TocActiveColorLabel": "Active Color",
    "TocTitleColorLabel": "Title Color",
    "TocLevelColorDimmingLabel": "Level Color Dimming",
    "TocBackgroundColorLabel": "Background Color",
    "TocBorderColorLabel": "Border Color",
    "TocContainerPaddingLabel": "Container Padding",
    "TocItemSpacingLabel": "Item Spacing",
    "TocIndentPerLevelLabel": "Indent Per Level",
    "TocMaxWidthLabel": "Max Width",
    "TocCustomIconLabel": "Custom Icon",
    "TocEnableScrollspyLabel": "Enable Scrollspy",
    "TocEnableCollapsibleLabel": "Collapsible Sections",
    "TocEnableHoverBackgroundLabel": "Hover Background",
    "TocHoverBackgroundColorLabel": "Hover Background Color",
    "TocEnableClickRippleLabel": "Click Ripple Effect",
    "TocStyleAccordionLabel": "TOC Style",
    "TocTypographyAccordionLabel": "Typography",
    "TocColorsAccordionLabel": "Colors",
    "TocSpacingAccordionLabel": "Spacing",
    "TocInteractionsAccordionLabel": "Interactions",

    // Configuration Panel strings (v3.7)
    "ConfigPanelButtonLabel": "Open Configuration Panel",
    "ConfigPanelTitle": "PiCanvas Configuration",

    // Profile Report strings (v4.0)
    "ProfileReportLibraryLabel": "Document Library",
    "ProfileReportLibraryDescription": "SharePoint library containing profile files (.md, .json)",
    "ProfileReportLayoutLabel": "Layout",
    "ProfileReportLayoutDescription": "How to display companies",
    "ProfileReportShowMethodKLabel": "Show Method-K",
    "ProfileReportShowMethodLLabel": "Show Method-L",
    "ProfileReportShowMethodMLabel": "Show Method-M (AI Synthesis)",
    "ProfileReportShowProfileJsonLabel": "Show Profile JSON",
    "ProfileReportCompanyLimitLabel": "Max Companies",
    "ProfileReportCompanyLimitDescription": "Maximum number of companies to display",
    "ProfileReportSortByLabel": "Sort By",
    "ProfileReportSortByDescription": "How to sort companies",
    "ProfileReportThemeLabel": "Theme",
    "ProfileReportThemeDescription": "Color theme for the report viewer",
    "ProfileReportLoadingMessage": "Loading company profiles...",
    "ProfileReportErrorMessage": "Failed to load profile reports",
    "ProfileReportNoDataMessage": "No companies found",

    // Profile Report list + display mode + metadata strings (v4.1)
    "ProfileReportListNameLabel": "Company List Name",
    "ProfileReportDisplayModeLabel": "Display Mode",
    "ProfileReportSidebarWidthLabel": "Sidebar Width",
    "ProfileReportEnableMetadataLabel": "Enable Metadata Discovery",
    "ProfileReportMetadataCompanyColLabel": "Company Column Name",
    "ProfileReportMetadataFileCategoryLabel": "File Category Column Name",
    "ProfileReportSidebarSearch": "Search companies...",
    "ProfileReportMetadataFiles": "Additional Files",
    "ProfileReportViewFile": "View"
  }
});
