define([], function () {
  return {
    "PropertyPaneDescription": "Infinite possibilities - Configure tabs to organize web parts from anywhere on the page.",
    "BasicGroupName": "Troubleshooting",
    "DescriptionFieldLabel": "Description Field",
    "SectionClass": "Section Selector",
    "WebPartClass": "Web Part Selector",
    "TabLabels": "Tab Labels",
    "ManageTabLabels": "Manage Tab Labels",
    "AppTitle": "PiCanvas",
    "OriginalAuthor": "Originally created by Mark Rackley",
    "UpgradedBy": "Upgraded by @anthonyrhopkins",

    // Template strings
    "TemplatesGroupName": "Templates",
    "TemplatesDescription": "Apply pre-built templates or export/import your configuration",
    "ApplyTemplateLabel": "Apply Template",
    "SelectTemplatePlaceholder": "-- Select a template --",
    "BuiltInTemplatesHeader": "--- Built-in Templates ---",
    "SavedTemplatesHeader": "--- Saved Templates ---",
    "ApplyTemplateButton": "Apply Selected Template",
    "ExportImportHeader": "Export / Import",
    "ExportConfigLabel": "Export Configuration",
    "ImportConfigLabel": "Import Configuration",
    "SaveAsTemplateLabel": "Save as Template",
    "TemplateNamePrompt": "Enter a name for this template:",
    "ExportSuccessMessage": "Configuration exported successfully!",
    "ImportSuccessMessage": "Configuration imported successfully! Please assign web parts to tabs.",
    "SaveTemplateSuccessMessage": "Template saved to Site Assets!",
    "ImportErrorMessage": "Failed to import configuration. Please check the file format.",
    "SaveTemplateErrorMessage": "Failed to save template. Please check your permissions.",
    "NoSiteAssetsAccess": "Site Assets not accessible. Saving templates to SharePoint is disabled, but you can still use Export/Import.",

    // Permission strings
    "PermissionHeaderLabel": "Permissions",
    "PermissionEnabledLabel": "Restrict by Group",
    "PermissionGroupsLabel": "Visible to Groups",
    "PermissionGroupsDescription": "Select which groups can see this tab",
    "PermissionCustomGroupsLabel": "Custom Group IDs",
    "PermissionCustomGroupsPlaceholder": "e.g. 5, 12, 23",
    "PermissionCustomGroupsDescription": "Enter SharePoint group IDs (comma-separated)",
    "PermissionVisibleToAll": "Everyone (no restriction)",
    "PermissionOwnersLabel": "Site Owners",
    "PermissionMembersLabel": "Site Members",
    "PermissionVisitorsLabel": "Site Visitors",
    "PermissionOwnersMembers": "Owners & Members",
    "PermissionMembersVisitors": "Members & Visitors",
    "PermissionAllGroups": "All Site Groups",

    // Permission placeholder strings
    "PermissionPlaceholderLabel": "Show Placeholder",
    "PermissionPlaceholderDescription": "Show disabled tab with message instead of hiding",
    "PermissionPlaceholderTextLabel": "Placeholder Message",
    "PermissionPlaceholderTextPlaceholder": "e.g. Access restricted",
    "PermissionPlaceholderDefault": "Restricted",

    // Lock strings
    "LockHeaderLabel": "Password Lock",
    "LockEnabledLabel": "Require Password",
    "LockEnabledOnText": "Locked",
    "LockEnabledOffText": "Unlocked",
    "LockPasswordSetLabel": "Password is set for this tab.",
    "LockPasswordMissingLabel": "No password set. This tab will stay locked until you set one.",
    "LockPasswordLabel": "Set or Update Password",
    "LockPasswordDescription": "Stored as a one-way hash in web part properties. This is a client-side lock.",
    "LockTemplateToggleLabel": "Customize Lock Screen HTML",
    "LockTemplateToggleOnText": "Custom",
    "LockTemplateToggleOffText": "Default",
    "LockTemplateLabel": "Lock Screen HTML",
    "LockTemplateDescription": "Include data-picanvas-lock-input, data-picanvas-lock-submit, data-picanvas-lock-message. Tokens: {{tabLabel}}, {{tabIndex}}, {{lockTitle}}, {{passwordLabel}}, {{unlockLabel}}.",
    "LockMessagesToggleLabel": "Customize Lock Messages",
    "LockMessagesToggleOnText": "Custom",
    "LockMessagesToggleOffText": "Default",
    "LockPromptMessageLabel": "Prompt Message (HTML)",
    "LockPromptMessageDescription": "Shown before the password is entered.",
    "LockErrorMessageLabel": "Error Message (HTML)",
    "LockErrorMessageDescription": "Shown after an incorrect password.",
    "LockMissingPasswordMessageLabel": "No Password Message (HTML)",
    "LockMissingPasswordMessageDescription": "Shown when no password is configured.",
    "LockSuccessMessageLabel": "Success Message (HTML)",
    "LockSuccessMessageDescription": "Shown briefly after unlocking.",
    "LockPromptMessage": "Enter the password to unlock this tab.",
    "LockErrorMessage": "Incorrect password. Please try again.",
    "LockMissingPasswordMessage": "No password has been set for this tab.",
    "LockSuccessMessage": "Unlocked.",
    "LockTitleText": "Protected content",
    "LockPasswordFieldLabel": "Password",
    "LockUnlockButtonLabel": "Unlock",

    // Lock default strings
    "LockDefaultsGroupName": "Lock Defaults",
    "LockDefaultsDescription": "Set default lock screen HTML and messages for all tabs. Tab-level overrides take precedence.",
    "LockUnlockTtlLabel": "Unlock Duration (minutes)",
    "LockUnlockTtlDescription": "How long an unlocked tab stays open in the current session (1-1440).",
    "LockDefaultTemplateToggleLabel": "Default Lock Screen HTML",
    "LockDefaultTemplateToggleOnText": "Custom",
    "LockDefaultTemplateToggleOffText": "Default",
    "LockDefaultTemplateLabel": "Default Lock Screen HTML",
    "LockDefaultTemplateDescription": "Must include data-picanvas-lock-input, data-picanvas-lock-submit, data-picanvas-lock-message. Tokens: {{tabLabel}}, {{tabIndex}}, {{lockTitle}}, {{passwordLabel}}, {{unlockLabel}}.",
    "LockDefaultMessagesToggleLabel": "Default Lock Messages",
    "LockDefaultMessagesToggleOnText": "Custom",
    "LockDefaultMessagesToggleOffText": "Default",
    "LockDefaultPromptMessageLabel": "Default Prompt Message (HTML)",
    "LockDefaultPromptMessageDescription": "Shown before the password is entered.",
    "LockDefaultErrorMessageLabel": "Default Error Message (HTML)",
    "LockDefaultErrorMessageDescription": "Shown after an incorrect password.",
    "LockDefaultMissingMessageLabel": "Default No Password Message (HTML)",
    "LockDefaultMissingMessageDescription": "Shown when no password is configured.",
    "LockDefaultSuccessMessageLabel": "Default Success Message (HTML)",
    "LockDefaultSuccessMessageDescription": "Shown briefly after unlocking.",

    // Content type strings (v3.0)
    "ContentTypeLabel": "Content Type",
    "ContentTypeWebPart": "SharePoint Web Part",
    "ContentTypeSection": "SharePoint Section",
    "ContentTypeMarkdown": "Markdown Content",
    "ContentTypeHtml": "HTML Content",
    "ContentTypeMermaid": "Mermaid Diagram",
    "ContentTypeEmbed": "Embed (iframe)",

    // Custom content strings (v3.0)
    "CustomContentLabel": "Content",
    "MarkdownPlaceholder": "Enter Markdown content...\n\n# Heading\n**Bold** and *italic* text\n- List item",
    "HtmlPlaceholder": "Enter HTML content...\n\n<div class=\"my-content\">\n  <h2>Title</h2>\n  <p>Your content here</p>\n</div>",
    "MermaidPlaceholder": "Enter Mermaid diagram code...\n\ngraph TD\n    A[Start] --> B{Decision}\n    B -->|Yes| C[Action]\n    B -->|No| D[End]",

    // Embed strings (v3.0)
    "EmbedUrlLabel": "Embed URL",
    "EmbedUrlDescription": "Enter a URL from a trusted domain (YouTube, Power BI, Forms, etc.)",
    "EmbedHeightLabel": "Embed Height",
    "EmbedHeightPlaceholder": "e.g. 400px, 50vh",
    "EmbedFullPageLabel": "Embed Layout",
    "EmbedFullPageOn": "Full Page",
    "EmbedFullPageOff": "Custom",
    "EmbedFullWidthLabel": "Embed Width",
    "EmbedFullWidthOn": "Full Width (edge-to-edge)",
    "EmbedFullWidthOff": "Contained",
    "EmbedFullHeightLabel": "Embed Height Mode",
    "EmbedFullHeightOn": "Full Height (100vh)",
    "EmbedFullHeightOff": "Custom Height",

    // External file strings (v3.1)
    "ContentTypeFile": "External File",
    "FileUrlLabel": "File URL",
    "FileUrlPlaceholder": "/sites/yoursite/SiteAssets/PiCanvas/content.html",
    "FileUrlDescription": "Server-relative path to .html or .md file",
    "BrowseSiteAssetsLabel": "Browse Site Assets",
    "FileLoadingMessage": "Loading content...",
    "FileUrlMissingMessage": "No file URL specified",
    "FileTypeUnsupportedMessage": "Unsupported file type. Use .html or .md files.",
    "FileSourceWebPartMissingMessage": "No Text WebPart selected. Please select a Text WebPart in the settings.",
    "FileSourceWebPartEmptyMessage": "The selected Text WebPart is empty or could not be read.",

    // Content source strings (v3.1)
    "ContentSourceTypeLabel": "Content Source",
    "ContentSourceManual": "Manual Input",
    "ContentSourceWebPart": "Text WebPart on Page",
    "ContentSourceWebPartLabel": "Select Text WebPart",
    "ContentSourceWebPartInfo": "The selected Text WebPart will be hidden and its content rendered here.",

    // RSS Feed strings (v3.2)
    "ContentTypeRss": "RSS Feed",
    "RssFeedUrlLabel": "Feed URL",
    "RssLayoutLabel": "Layout",
    "RssMaxItemsLabel": "Max Items",
    "RssShowDateLabel": "Show Date",
    "RssShowDescriptionLabel": "Show Description",
    "RssShowImageLabel": "Show Image",
    "RssShowAuthorLabel": "Show Author",
    "RssDescriptionLimitLabel": "Description Length",
    "RssDateFormatLabel": "Date Format",
    "RssLinkTargetLabel": "Open Links In",
    "RssLoadingMessageLabel": "Loading Message",

    // Feature toggle strings (v3.0)
    "EnableDeepLinkingLabel": "Enable URL Deep Linking",
    "EnableDeepLinkingDescription": "Allow linking directly to tabs via URL hash (e.g. #tab-name)",
    "EnableLazyLoadingLabel": "Enable Lazy Loading",
    "EnableLazyLoadingDescription": "Delay loading tab content until tab is activated",

    // Accessibility strings (v3.0)
    "TabListAriaLabel": "Content sections"
  }
});
