/**
 * JavaScript Templates for PiCanvas
 * Built-in templates that users can select and configure directly in the property pane
 */

// ============================================================================
// Interfaces
// ============================================================================

export interface IJavaScriptTemplateConfig {
  [key: string]: string | number | boolean | object[];
}

export interface IJavaScriptTemplateOption {
  key: string;
  label: string;
  type: 'text' | 'textarea' | 'color' | 'number' | 'dropdown' | 'toggle';
  default: string | number | boolean;
  description?: string;
  options?: { key: string; text: string }[]; // For dropdown type
  min?: number; // For number type
  max?: number; // For number type
}

export interface IJavaScriptTemplate {
  id: string;
  name: string;
  description: string;
  category: 'landing' | 'dashboard' | 'content' | 'layout';
  icon: string; // Emoji icon for display
  configOptions: IJavaScriptTemplateOption[];
  generateCode: (config: IJavaScriptTemplateConfig) => string;
}

// ============================================================================
// Built-in Templates
// ============================================================================

/**
 * Landing Page Template
 * Full landing page with hero section, animated timeline, and CTA
 */
const landingPageTemplate: IJavaScriptTemplate = {
  id: 'landing-page',
  name: 'Landing Page',
  description: 'Full landing page with hero, animated timeline, and CTA section',
  category: 'landing',
  icon: '🎨',
  configOptions: [
    { key: 'brandName', label: 'Brand Name', type: 'text', default: 'My Brand', description: 'Company or site name' },
    { key: 'brandInitials', label: 'Brand Initials', type: 'text', default: 'MB', description: 'Avatar initials (2 chars)' },
    { key: 'heroTitle', label: 'Hero Title (Line 1)', type: 'text', default: 'Your digital', description: 'First line of hero title' },
    { key: 'heroTitleGradient', label: 'Hero Title (Line 2)', type: 'text', default: 'workspace', description: 'Second line with gradient effect' },
    { key: 'heroDescription', label: 'Hero Description', type: 'textarea', default: 'Manage documents, collaborate with your team, and boost productivity with our modern platform.', description: 'Hero section description' },
    { key: 'primaryColor', label: 'Primary Color', type: 'color', default: '#ec4899', description: 'Main accent color' },
    { key: 'backgroundColor', label: 'Background Color', type: 'color', default: '#0a1628', description: 'Page background color' },
    { key: 'ctaTitle', label: 'CTA Title', type: 'text', default: 'Ready to get started?', description: 'Call-to-action section title' },
    { key: 'ctaButtonText', label: 'CTA Button Text', type: 'text', default: 'Start Free Trial', description: 'Main CTA button text' },
    { key: 'showTimeline', label: 'Show Timeline', type: 'toggle', default: true, description: 'Display animated feature timeline' },
  ],
  generateCode: (config: IJavaScriptTemplateConfig) => {
    const brandName = String(config.brandName || 'My Brand');
    const brandInitials = String(config.brandInitials || 'MB').substring(0, 2);
    const heroTitle = String(config.heroTitle || 'Your digital');
    const heroTitleGradient = String(config.heroTitleGradient || 'workspace');
    const heroDescription = String(config.heroDescription || 'Manage documents, collaborate with your team, and boost productivity.');
    const primaryColor = String(config.primaryColor || '#ec4899');
    const backgroundColor = String(config.backgroundColor || '#0a1628');
    const ctaTitle = String(config.ctaTitle || 'Ready to get started?');
    const ctaButtonText = String(config.ctaButtonText || 'Start Free Trial');
    const showTimeline = config.showTimeline !== false;

    return `// Landing Page Template - Generated by PiCanvas
// Primary: ${primaryColor} | Background: ${backgroundColor}

(function() {
  const config = {
    brandName: ${JSON.stringify(brandName)},
    brandInitials: ${JSON.stringify(brandInitials)},
    heroTitle: ${JSON.stringify(heroTitle)},
    heroTitleGradient: ${JSON.stringify(heroTitleGradient)},
    heroDescription: ${JSON.stringify(heroDescription)},
    primaryColor: ${JSON.stringify(primaryColor)},
    backgroundColor: ${JSON.stringify(backgroundColor)},
    ctaTitle: ${JSON.stringify(ctaTitle)},
    ctaButtonText: ${JSON.stringify(ctaButtonText)},
    showTimeline: ${showTimeline}
  };

  // Feature nodes for timeline
  const nodes = [
    { id: 1, title: "Documents", description: "Manage and share all your important files in one place.", icon: "fileText", stats: "2,847 Files" },
    { id: 2, title: "Team", description: "Collaborate with your team in real-time - efficient and transparent.", icon: "users", stats: "24 Members" },
    { id: 3, title: "Calendar", description: "Keep track of appointments, meetings, and deadlines.", icon: "calendar", stats: "12 Events" },
    { id: 4, title: "Analytics", description: "Data-driven insights for better decisions.", icon: "barChart", stats: "+34% Growth" },
    { id: 5, title: "Projects", description: "Project management and task tracking in one interface.", icon: "folder", stats: "8 Active" },
    { id: 6, title: "Communication", description: "Seamless communication with integrated chat and messaging.", icon: "messageSquare", stats: "156 Messages" }
  ];

  // SVG Icons
  const icons = {
    zap: '<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><polygon points="13 2 3 14 12 14 11 22 21 10 12 10 13 2"/></svg>',
    fileText: '<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"/><polyline points="14 2 14 8 20 8"/><line x1="16" y1="13" x2="8" y2="13"/><line x1="16" y1="17" x2="8" y2="17"/></svg>',
    users: '<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M17 21v-2a4 4 0 0 0-4-4H5a4 4 0 0 0-4 4v2"/><circle cx="9" cy="7" r="4"/><path d="M23 21v-2a4 4 0 0 0-3-3.87"/><path d="M16 3.13a4 4 0 0 1 0 7.75"/></svg>',
    calendar: '<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><rect x="3" y="4" width="18" height="18" rx="2" ry="2"/><line x1="16" y1="2" x2="16" y2="6"/><line x1="8" y1="2" x2="8" y2="6"/><line x1="3" y1="10" x2="21" y2="10"/></svg>',
    barChart: '<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><line x1="12" y1="20" x2="12" y2="10"/><line x1="18" y1="20" x2="18" y2="4"/><line x1="6" y1="20" x2="6" y2="16"/></svg>',
    folder: '<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M22 19a2 2 0 0 1-2 2H4a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h5l2 3h9a2 2 0 0 1 2 2z"/></svg>',
    messageSquare: '<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M21 15a2 2 0 0 1-2 2H7l-4 4V5a2 2 0 0 1 2-2h14a2 2 0 0 1 2 2z"/></svg>',
    arrowRight: '<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><line x1="5" y1="12" x2="19" y2="12"/><polyline points="12 5 19 12 12 19"/></svg>',
    search: '<svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><circle cx="11" cy="11" r="8"/><line x1="21" y1="21" x2="16.65" y2="16.65"/></svg>',
    bell: '<svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M18 8A6 6 0 0 0 6 8c0 7-3 9-3 9h18s-3-2-3-9"/><path d="M13.73 21a2 2 0 0 1-3.46 0"/></svg>'
  };

  // Create snake path for timeline
  function createSnakePath() {
    const points = [];
    const totalHeight = 2600;
    const segments = 6;
    const segmentHeight = totalHeight / segments;
    points.push('M 200 0');
    for (let i = 0; i < segments; i++) {
      const startY = i * segmentHeight;
      const endY = startY + segmentHeight;
      const isGoingRight = i % 2 === 0;
      if (isGoingRight) {
        points.push('C 200 ' + (startY + segmentHeight * 0.3) + ', 350 ' + (startY + segmentHeight * 0.3) + ', 350 ' + (startY + segmentHeight * 0.5));
        points.push('C 350 ' + (startY + segmentHeight * 0.7) + ', 200 ' + (startY + segmentHeight * 0.7) + ', 200 ' + endY);
      } else {
        points.push('C 200 ' + (startY + segmentHeight * 0.3) + ', 50 ' + (startY + segmentHeight * 0.3) + ', 50 ' + (startY + segmentHeight * 0.5));
        points.push('C 50 ' + (startY + segmentHeight * 0.7) + ', 200 ' + (startY + segmentHeight * 0.7) + ', 200 ' + endY);
      }
    }
    return points.join(' ');
  }

  // Escape HTML
  function escapeHtml(str) {
    return String(str).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');
  }

  // Build the page
  const snakePath = createSnakePath();

  let html = '<style>' +
    ':root { --lp-primary: ' + config.primaryColor + '; --lp-bg: ' + config.backgroundColor + '; }' +
    '.lp-container { font-family: "Segoe UI", -apple-system, BlinkMacSystemFont, sans-serif; background: var(--lp-bg); color: #fff; min-height: 100vh; position: relative; overflow-x: hidden; }' +
    '.lp-background { position: fixed; inset: 0; z-index: 0; overflow: hidden; }' +
    '.lp-blob { position: absolute; border-radius: 50%; filter: blur(120px); opacity: 0.4; }' +
    '.lp-blob--pink { width: 600px; height: 600px; background: var(--lp-primary); top: -200px; right: -200px; animation: float 15s ease-in-out infinite; }' +
    '.lp-blob--blue { width: 500px; height: 500px; background: #3b82f6; bottom: -150px; left: -150px; animation: float 18s ease-in-out infinite reverse; }' +
    '@keyframes float { 0%, 100% { transform: translate(0, 0); } 50% { transform: translate(30px, 30px); } }' +
    '.lp-header { position: fixed; top: 0; left: 0; right: 0; z-index: 100; padding: 1rem 2rem; background: rgba(10, 22, 40, 0.8); backdrop-filter: blur(12px); border-bottom: 1px solid rgba(255,255,255,0.1); }' +
    '.lp-header__inner { max-width: 1400px; margin: 0 auto; display: flex; align-items: center; justify-content: space-between; }' +
    '.lp-logo { display: flex; align-items: center; gap: 12px; font-size: 1.25rem; font-weight: 600; }' +
    '.lp-logo__icon { width: 36px; height: 36px; background: linear-gradient(135deg, var(--lp-primary), #8b5cf6); border-radius: 10px; display: flex; align-items: center; justify-content: center; }' +
    '.lp-nav { display: flex; gap: 32px; }' +
    '.lp-nav__link { color: rgba(255,255,255,0.7); text-decoration: none; font-size: 0.9rem; transition: color 0.2s; }' +
    '.lp-nav__link:hover { color: #fff; }' +
    '.lp-header__actions { display: flex; align-items: center; gap: 16px; }' +
    '.lp-icon-btn { width: 40px; height: 40px; border: none; background: rgba(255,255,255,0.1); border-radius: 10px; display: flex; align-items: center; justify-content: center; cursor: pointer; color: rgba(255,255,255,0.8); transition: all 0.2s; position: relative; }' +
    '.lp-icon-btn:hover { background: rgba(255,255,255,0.15); color: #fff; }' +
    '.lp-icon-btn__badge { position: absolute; top: 6px; right: 6px; width: 8px; height: 8px; background: var(--lp-primary); border-radius: 50%; }' +
    '.lp-avatar { width: 40px; height: 40px; background: linear-gradient(135deg, var(--lp-primary), #8b5cf6); border-radius: 50%; display: flex; align-items: center; justify-content: center; font-weight: 600; font-size: 0.9rem; }' +
    '.lp-hero { position: relative; z-index: 1; min-height: 100vh; display: flex; flex-direction: column; align-items: center; justify-content: center; text-align: center; padding: 120px 24px 80px; }' +
    '.lp-badge { display: inline-block; padding: 8px 16px; background: rgba(255,255,255,0.1); border-radius: 100px; font-size: 0.85rem; color: rgba(255,255,255,0.9); margin-bottom: 24px; backdrop-filter: blur(8px); border: 1px solid rgba(255,255,255,0.1); }' +
    '.lp-hero__title { font-size: clamp(2.5rem, 6vw, 4.5rem); font-weight: 700; line-height: 1.1; margin: 0 0 24px; }' +
    '.lp-hero__title-gradient { display: block; background: linear-gradient(135deg, var(--lp-primary), #a855f7, #3b82f6); -webkit-background-clip: text; -webkit-text-fill-color: transparent; background-clip: text; }' +
    '.lp-hero__description { font-size: 1.25rem; color: rgba(255,255,255,0.7); max-width: 600px; margin: 0 0 40px; line-height: 1.6; }' +
    '.lp-hero__buttons { display: flex; gap: 16px; flex-wrap: wrap; justify-content: center; }' +
    '.lp-btn { padding: 14px 28px; border-radius: 12px; font-size: 1rem; font-weight: 500; cursor: pointer; transition: all 0.2s; border: none; }' +
    '.lp-btn--primary { background: linear-gradient(135deg, var(--lp-primary), #a855f7); color: #fff; box-shadow: 0 4px 20px rgba(236, 72, 153, 0.4); }' +
    '.lp-btn--primary:hover { transform: translateY(-2px); box-shadow: 0 6px 30px rgba(236, 72, 153, 0.5); }' +
    '.lp-btn--secondary { background: rgba(255,255,255,0.1); color: #fff; border: 1px solid rgba(255,255,255,0.2); backdrop-filter: blur(8px); }' +
    '.lp-btn--secondary:hover { background: rgba(255,255,255,0.15); }' +
    '.lp-intro-line { margin-top: 60px; display: flex; flex-direction: column; align-items: center; }' +
    '.lp-intro-line__line { width: 2px; height: 80px; background: linear-gradient(to bottom, var(--lp-primary), transparent); }' +
    '.lp-intro-line__dot { width: 12px; height: 12px; background: var(--lp-primary); border-radius: 50%; animation: pulse 2s infinite; }' +
    '@keyframes pulse { 0%, 100% { transform: scale(1); opacity: 1; } 50% { transform: scale(1.5); opacity: 0.5; } }' +
    '.lp-scroll-hint { margin-top: 20px; font-size: 0.9rem; color: rgba(255,255,255,0.5); animation: bounce 2s infinite; }' +
    '@keyframes bounce { 0%, 100% { transform: translateY(0); } 50% { transform: translateY(8px); } }' +
    '.lp-timeline { position: relative; z-index: 1; padding: 100px 0 200px; }' +
    '.lp-timeline__inner { position: relative; max-width: 1200px; margin: 0 auto; }' +
    '.lp-timeline__title { text-align: center; margin-bottom: 80px; }' +
    '.lp-timeline__title h2 { font-size: 2.5rem; font-weight: 700; opacity: 0; transform: translateY(30px); transition: all 0.8s cubic-bezier(0.4, 0, 0.2, 1); }' +
    '.lp-timeline__title h2.lp-in-view { opacity: 1; transform: translateY(0); }' +
    '.lp-snake-container { position: absolute; left: 50%; transform: translateX(-50%); z-index: 1; }' +
    '.lp-snake-path { transition: stroke-dashoffset 0.1s linear; }' +
    '.lp-snake-path--bg { stroke: rgba(255,255,255,0.1); }' +
    '.lp-snake-path--glow { stroke: var(--lp-primary); filter: blur(8px); opacity: 0.5; }' +
    '.lp-nodes-container { position: relative; z-index: 2; height: 2800px; }' +
    '.lp-pink-node { position: absolute; width: 32px; height: 32px; transform: translateX(-50%); z-index: 3; opacity: 0; transition: all 0.6s cubic-bezier(0.4, 0, 0.2, 1); }' +
    '.lp-pink-node--right { left: calc(50% + 150px); }' +
    '.lp-pink-node--left { left: calc(50% - 150px); }' +
    '.lp-pink-node.lp-in-view { opacity: 1; }' +
    '.lp-pink-node__outer, .lp-pink-node__middle, .lp-pink-node__core { position: absolute; border-radius: 50%; left: 50%; top: 50%; transform: translate(-50%, -50%); }' +
    '.lp-pink-node__outer { width: 32px; height: 32px; background: radial-gradient(circle, rgba(236, 72, 153, 0.3), transparent 70%); animation: pulseOuter 2s ease-in-out infinite; }' +
    '.lp-pink-node__middle { width: 20px; height: 20px; background: radial-gradient(circle, rgba(236, 72, 153, 0.5), rgba(236, 72, 153, 0.2)); animation: pulseMiddle 2s ease-in-out infinite 0.3s; }' +
    '.lp-pink-node__core { width: 10px; height: 10px; background: var(--lp-primary); box-shadow: 0 0 20px var(--lp-primary); }' +
    '@keyframes pulseOuter { 0%, 100% { transform: translate(-50%, -50%) scale(1); opacity: 0.5; } 50% { transform: translate(-50%, -50%) scale(1.3); opacity: 0.3; } }' +
    '@keyframes pulseMiddle { 0%, 100% { transform: translate(-50%, -50%) scale(1); } 50% { transform: translate(-50%, -50%) scale(1.2); } }' +
    '.lp-content-card { position: absolute; width: 380px; opacity: 0; transform: translateX(30px); transition: all 0.6s cubic-bezier(0.4, 0, 0.2, 1); }' +
    '.lp-content-card--left { right: calc(50% + 100px); transform: translateX(-30px); }' +
    '.lp-content-card--right { left: calc(50% + 100px); }' +
    '.lp-content-card.lp-in-view { opacity: 1; transform: translateX(0); }' +
    '.lp-card { background: rgba(255,255,255,0.05); backdrop-filter: blur(12px); border-radius: 20px; padding: 28px; border: 1px solid rgba(255,255,255,0.1); transition: all 0.3s; }' +
    '.lp-card:hover { transform: translateY(-4px); border-color: rgba(236, 72, 153, 0.3); box-shadow: 0 20px 40px rgba(0,0,0,0.2); }' +
    '.lp-card__header { display: flex; align-items: flex-start; gap: 16px; margin-bottom: 16px; }' +
    '.lp-card__icon { width: 48px; height: 48px; background: linear-gradient(135deg, var(--lp-primary), #a855f7); border-radius: 14px; display: flex; align-items: center; justify-content: center; flex-shrink: 0; }' +
    '.lp-card__info { flex: 1; }' +
    '.lp-card__title { font-size: 1.25rem; font-weight: 600; margin: 0 0 4px; }' +
    '.lp-card__stats { font-size: 0.85rem; color: var(--lp-primary); }' +
    '.lp-card__description { color: rgba(255,255,255,0.7); line-height: 1.6; margin: 0 0 20px; }' +
    '.lp-card__cta { display: inline-flex; align-items: center; gap: 8px; color: var(--lp-primary); font-weight: 500; cursor: pointer; transition: gap 0.2s; }' +
    '.lp-card__cta:hover { gap: 12px; }' +
    '.lp-timeline__end { position: absolute; left: 50%; transform: translateX(-50%); opacity: 0; transition: all 0.8s; }' +
    '.lp-timeline__end.lp-in-view { opacity: 1; }' +
    '.lp-timeline__end-icon { width: 64px; height: 64px; background: linear-gradient(135deg, var(--lp-primary), #8b5cf6); border-radius: 50%; display: flex; align-items: center; justify-content: center; box-shadow: 0 0 40px rgba(236, 72, 153, 0.5); }' +
    '.lp-cta { position: relative; z-index: 1; padding: 100px 24px; }' +
    '.lp-cta__inner { max-width: 900px; margin: 0 auto; }' +
    '.lp-cta__card { position: relative; background: rgba(255,255,255,0.05); backdrop-filter: blur(16px); border-radius: 32px; padding: 64px; text-align: center; border: 1px solid rgba(255,255,255,0.1); overflow: hidden; opacity: 0; transform: translateY(30px); transition: all 0.8s cubic-bezier(0.4, 0, 0.2, 1); }' +
    '.lp-cta__card.lp-in-view { opacity: 1; transform: translateY(0); }' +
    '.lp-cta__sweep { position: absolute; inset: 0; background: linear-gradient(90deg, transparent, rgba(255,255,255,0.1), transparent); transform: translateX(-100%); }' +
    '.lp-cta__card:hover .lp-cta__sweep { animation: sweep 1s forwards; }' +
    '@keyframes sweep { to { transform: translateX(100%); } }' +
    '.lp-cta__title { font-size: 2.5rem; font-weight: 700; margin: 0 0 16px; }' +
    '.lp-cta__description { font-size: 1.1rem; color: rgba(255,255,255,0.7); margin: 0 0 32px; }' +
    '.lp-footer { position: relative; z-index: 1; padding: 40px 24px; border-top: 1px solid rgba(255,255,255,0.1); }' +
    '.lp-footer__inner { max-width: 1400px; margin: 0 auto; display: flex; align-items: center; justify-content: space-between; flex-wrap: wrap; gap: 16px; }' +
    '.lp-footer__logo { display: flex; align-items: center; gap: 10px; }' +
    '.lp-footer__logo-icon { width: 28px; height: 28px; background: linear-gradient(135deg, var(--lp-primary), #8b5cf6); border-radius: 8px; display: flex; align-items: center; justify-content: center; }' +
    '.lp-footer__logo-text { font-weight: 600; }' +
    '.lp-footer__copyright { color: rgba(255,255,255,0.5); font-size: 0.9rem; }' +
    '@media (max-width: 900px) { .lp-nav { display: none; } .lp-content-card { width: 280px; } .lp-content-card--left { right: calc(50% + 40px); } .lp-content-card--right { left: calc(50% + 40px); } }' +
    '@media (max-width: 600px) { .lp-content-card { position: relative; width: 100%; max-width: 380px; left: auto !important; right: auto !important; top: auto !important; margin: 20px auto; } .lp-snake-container { display: none; } .lp-pink-node { display: none; } .lp-nodes-container { height: auto; display: flex; flex-direction: column; gap: 20px; padding: 0 20px; } .lp-timeline__end { position: relative; margin-top: 40px; } }' +
    '</style>';

  html += '<div class="lp-container">' +
    '<div class="lp-background"><div class="lp-blob lp-blob--pink"></div><div class="lp-blob lp-blob--blue"></div></div>' +
    '<header class="lp-header"><div class="lp-header__inner">' +
    '<div class="lp-logo"><div class="lp-logo__icon">' + icons.zap + '</div><span>' + escapeHtml(config.brandName) + '</span></div>' +
    '<nav class="lp-nav"><a href="#" class="lp-nav__link">Start</a><a href="#" class="lp-nav__link">Documents</a><a href="#" class="lp-nav__link">Team</a><a href="#" class="lp-nav__link">Settings</a></nav>' +
    '<div class="lp-header__actions"><button class="lp-icon-btn">' + icons.search + '</button><button class="lp-icon-btn">' + icons.bell + '<span class="lp-icon-btn__badge"></span></button><div class="lp-avatar">' + escapeHtml(config.brandInitials) + '</div></div>' +
    '</div></header>' +
    '<section class="lp-hero"><div class="lp-hero__content">' +
    '<span class="lp-badge">Welcome to ' + escapeHtml(config.brandName) + '</span>' +
    '<h1 class="lp-hero__title">' + escapeHtml(config.heroTitle) + '<span class="lp-hero__title-gradient">' + escapeHtml(config.heroTitleGradient) + '</span></h1>' +
    '<p class="lp-hero__description">' + escapeHtml(config.heroDescription) + '</p>' +
    '<div class="lp-hero__buttons"><button class="lp-btn lp-btn--primary">Get Started</button><button class="lp-btn lp-btn--secondary">Learn More</button></div>' +
    '<div class="lp-intro-line"><div class="lp-intro-line__line"></div><div class="lp-intro-line__dot"></div></div>' +
    '<p class="lp-scroll-hint">Scroll to discover more</p>' +
    '</div></section>';

  if (config.showTimeline) {
    html += '<section class="lp-timeline" data-timeline><div class="lp-timeline__inner">' +
      '<div class="lp-timeline__title"><h2>Discover Our Features</h2></div>' +
      '<svg class="lp-snake-container" width="400" height="2600" style="overflow:visible;">' +
      '<path class="lp-snake-path lp-snake-path--bg" d="' + snakePath + '" fill="none" stroke-width="3" stroke-linecap="round"/>' +
      '<path class="lp-snake-path lp-snake-path--glow" d="' + snakePath + '" fill="none" stroke-width="6" stroke-linecap="round"/>' +
      '<path class="lp-snake-path" data-snake d="' + snakePath + '" fill="none" stroke="url(#lpLineGradient)" stroke-width="3" stroke-linecap="round"/>' +
      '<defs><linearGradient id="lpLineGradient" x1="0%" y1="0%" x2="0%" y2="100%"><stop offset="0%" stop-color="#ffffff"/><stop offset="50%" stop-color="#ffffff"/><stop offset="100%" stop-color="' + config.primaryColor + '"/></linearGradient></defs>' +
      '</svg>' +
      '<div class="lp-nodes-container">';

    nodes.forEach(function(node, index) {
      var posClass = index % 2 === 0 ? 'lp-pink-node--right' : 'lp-pink-node--left';
      var cardClass = index % 2 === 0 ? 'lp-content-card--left' : 'lp-content-card--right';
      html += '<div class="lp-pink-node ' + posClass + '" style="top:' + (index * 400 + 300) + 'px;" data-index="' + index + '"><div class="lp-pink-node__outer"></div><div class="lp-pink-node__middle"></div><div class="lp-pink-node__core"></div></div>';
      html += '<div class="lp-content-card ' + cardClass + '" style="top:' + (index * 400 + 100) + 'px;" data-node-id="' + node.id + '">' +
        '<div class="lp-card"><div class="lp-card__header">' +
        '<div class="lp-card__icon">' + (icons[node.icon] || icons.zap) + '</div>' +
        '<div class="lp-card__info"><h3 class="lp-card__title">' + escapeHtml(node.title) + '</h3><span class="lp-card__stats">' + escapeHtml(node.stats) + '</span></div>' +
        '</div><p class="lp-card__description">' + escapeHtml(node.description) + '</p>' +
        '<div class="lp-card__cta"><span>Learn more</span>' + icons.arrowRight + '</div></div></div>';
    });

    html += '<div class="lp-timeline__end" style="top:' + (nodes.length * 400 + 200) + 'px;"><div class="lp-timeline__end-icon">' + icons.zap + '</div></div>' +
      '</div></div></section>';
  }

  html += '<section class="lp-cta"><div class="lp-cta__inner"><div class="lp-cta__card">' +
    '<div class="lp-cta__sweep"></div>' +
    '<h2 class="lp-cta__title">' + escapeHtml(config.ctaTitle) + '</h2>' +
    '<p class="lp-cta__description">Start today and experience a new way of collaboration.</p>' +
    '<button class="lp-btn lp-btn--primary">' + escapeHtml(config.ctaButtonText) + '</button>' +
    '</div></div></section>' +
    '<footer class="lp-footer"><div class="lp-footer__inner">' +
    '<div class="lp-footer__logo"><div class="lp-footer__logo-icon">' + icons.zap + '</div><span class="lp-footer__logo-text">' + escapeHtml(config.brandName) + '</span></div>' +
    '<p class="lp-footer__copyright">&copy; ' + new Date().getFullYear() + ' ' + escapeHtml(config.brandName) + '. All rights reserved.</p>' +
    '</div></footer></div>';

  container.innerHTML = html;

  // Set up animations
  var prefersReducedMotion = window.matchMedia('(prefers-reduced-motion: reduce)').matches;
  var timeline = container.querySelector('[data-timeline]');
  var snakePathEl = container.querySelector('[data-snake]');
  var snakePathGlow = container.querySelector('.lp-snake-path--glow');

  if (snakePathEl && timeline) {
    var pathLength = snakePathEl.getTotalLength();
    snakePathEl.style.strokeDasharray = pathLength;
    snakePathEl.style.strokeDashoffset = prefersReducedMotion ? 0 : pathLength;
    if (snakePathGlow) {
      snakePathGlow.style.strokeDasharray = pathLength;
      snakePathGlow.style.strokeDashoffset = prefersReducedMotion ? 0 : pathLength;
    }

    if (!prefersReducedMotion) {
      function handleScroll() {
        var rect = timeline.getBoundingClientRect();
        var windowHeight = window.innerHeight;
        var scrollStart = rect.top - windowHeight;
        var scrollEnd = rect.top + rect.height;
        var scrollRange = scrollEnd - scrollStart;
        var currentScroll = -scrollStart;
        var progress = Math.max(0, Math.min(1, currentScroll / scrollRange));
        var offset = pathLength * (1 - progress);
        snakePathEl.style.strokeDashoffset = offset;
        if (snakePathGlow) snakePathGlow.style.strokeDashoffset = offset;
      }
      window.addEventListener('scroll', handleScroll, { passive: true });
      handleScroll();
    }
  }

  // Intersection Observer for animations
  var observerOptions = { threshold: 0.2, rootMargin: '-10% 0px -10% 0px' };
  var fadeInObserver = new IntersectionObserver(function(entries) {
    entries.forEach(function(entry) {
      if (entry.isIntersecting) entry.target.classList.add('lp-in-view');
    });
  }, observerOptions);

  var toggleObserver = new IntersectionObserver(function(entries) {
    entries.forEach(function(entry) {
      if (entry.isIntersecting) {
        entry.target.classList.add('lp-in-view');
      } else if (!prefersReducedMotion) {
        entry.target.classList.remove('lp-in-view');
      }
    });
  }, { threshold: 0.3, rootMargin: '-15% 0px -15% 0px' });

  container.querySelectorAll('.lp-timeline__title h2, .lp-timeline__end, .lp-cta__card').forEach(function(el) { fadeInObserver.observe(el); });
  container.querySelectorAll('.lp-content-card, .lp-pink-node').forEach(function(el) { toggleObserver.observe(el); });
})();`;
  }
};

/**
 * Stats Dashboard Template
 * Displays key metrics in card format with icons
 */
const statsDashboardTemplate: IJavaScriptTemplate = {
  id: 'stats-dashboard',
  name: 'Stats Dashboard',
  description: 'Display key metrics and statistics in modern card layout',
  category: 'dashboard',
  icon: '📊',
  configOptions: [
    { key: 'title', label: 'Dashboard Title', type: 'text', default: 'Dashboard Overview', description: 'Main heading' },
    { key: 'primaryColor', label: 'Primary Color', type: 'color', default: '#3b82f6', description: 'Accent color for cards' },
    { key: 'backgroundColor', label: 'Background Color', type: 'color', default: '#0f172a', description: 'Page background' },
    { key: 'stat1Label', label: 'Stat 1 Label', type: 'text', default: 'Total Users', description: 'First stat label' },
    { key: 'stat1Value', label: 'Stat 1 Value', type: 'text', default: '12,847', description: 'First stat value' },
    { key: 'stat1Trend', label: 'Stat 1 Trend', type: 'text', default: '+12%', description: 'First stat trend' },
    { key: 'stat2Label', label: 'Stat 2 Label', type: 'text', default: 'Revenue', description: 'Second stat label' },
    { key: 'stat2Value', label: 'Stat 2 Value', type: 'text', default: '$84,392', description: 'Second stat value' },
    { key: 'stat2Trend', label: 'Stat 2 Trend', type: 'text', default: '+8.2%', description: 'Second stat trend' },
    { key: 'stat3Label', label: 'Stat 3 Label', type: 'text', default: 'Active Projects', description: 'Third stat label' },
    { key: 'stat3Value', label: 'Stat 3 Value', type: 'text', default: '48', description: 'Third stat value' },
    { key: 'stat3Trend', label: 'Stat 3 Trend', type: 'text', default: '+3', description: 'Third stat trend' },
    { key: 'stat4Label', label: 'Stat 4 Label', type: 'text', default: 'Tasks Done', description: 'Fourth stat label' },
    { key: 'stat4Value', label: 'Stat 4 Value', type: 'text', default: '1,284', description: 'Fourth stat value' },
    { key: 'stat4Trend', label: 'Stat 4 Trend', type: 'text', default: '+24%', description: 'Fourth stat trend' },
  ],
  generateCode: (config: IJavaScriptTemplateConfig) => {
    return `// Stats Dashboard Template - Generated by PiCanvas
(function() {
  const config = ${JSON.stringify(config, null, 2)};

  const icons = {
    users: '<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M17 21v-2a4 4 0 0 0-4-4H5a4 4 0 0 0-4 4v2"/><circle cx="9" cy="7" r="4"/><path d="M23 21v-2a4 4 0 0 0-3-3.87"/><path d="M16 3.13a4 4 0 0 1 0 7.75"/></svg>',
    dollar: '<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><line x1="12" y1="1" x2="12" y2="23"/><path d="M17 5H9.5a3.5 3.5 0 0 0 0 7h5a3.5 3.5 0 0 1 0 7H6"/></svg>',
    folder: '<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M22 19a2 2 0 0 1-2 2H4a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h5l2 3h9a2 2 0 0 1 2 2z"/></svg>',
    check: '<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><polyline points="9 11 12 14 22 4"/><path d="M21 12v7a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h11"/></svg>',
    trendUp: '<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><polyline points="23 6 13.5 15.5 8.5 10.5 1 18"/><polyline points="17 6 23 6 23 12"/></svg>'
  };

  const stats = [
    { label: config.stat1Label || 'Total Users', value: config.stat1Value || '12,847', trend: config.stat1Trend || '+12%', icon: 'users' },
    { label: config.stat2Label || 'Revenue', value: config.stat2Value || '$84,392', trend: config.stat2Trend || '+8.2%', icon: 'dollar' },
    { label: config.stat3Label || 'Active Projects', value: config.stat3Value || '48', trend: config.stat3Trend || '+3', icon: 'folder' },
    { label: config.stat4Label || 'Tasks Done', value: config.stat4Value || '1,284', trend: config.stat4Trend || '+24%', icon: 'check' }
  ];

  function escapeHtml(str) { return String(str).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;'); }

  let html = '<style>' +
    ':root { --sd-primary: ' + (config.primaryColor || '#3b82f6') + '; --sd-bg: ' + (config.backgroundColor || '#0f172a') + '; }' +
    '.sd-container { font-family: "Segoe UI", -apple-system, sans-serif; background: var(--sd-bg); min-height: 100vh; padding: 40px; }' +
    '.sd-title { color: #fff; font-size: 2rem; font-weight: 700; margin: 0 0 32px; }' +
    '.sd-grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(280px, 1fr)); gap: 24px; }' +
    '.sd-card { background: rgba(255,255,255,0.05); border: 1px solid rgba(255,255,255,0.1); border-radius: 16px; padding: 24px; transition: all 0.3s; }' +
    '.sd-card:hover { transform: translateY(-4px); border-color: var(--sd-primary); box-shadow: 0 20px 40px rgba(0,0,0,0.3); }' +
    '.sd-card__header { display: flex; justify-content: space-between; align-items: flex-start; margin-bottom: 16px; }' +
    '.sd-card__icon { width: 48px; height: 48px; background: linear-gradient(135deg, var(--sd-primary), rgba(59, 130, 246, 0.5)); border-radius: 12px; display: flex; align-items: center; justify-content: center; color: #fff; }' +
    '.sd-card__trend { display: flex; align-items: center; gap: 4px; color: #22c55e; font-size: 0.875rem; font-weight: 500; }' +
    '.sd-card__value { font-size: 2.5rem; font-weight: 700; color: #fff; margin: 0 0 4px; }' +
    '.sd-card__label { color: rgba(255,255,255,0.6); font-size: 0.9rem; }' +
    '</style>';

  html += '<div class="sd-container">' +
    '<h1 class="sd-title">' + escapeHtml(config.title || 'Dashboard Overview') + '</h1>' +
    '<div class="sd-grid">';

  stats.forEach(function(stat) {
    html += '<div class="sd-card">' +
      '<div class="sd-card__header">' +
      '<div class="sd-card__icon">' + icons[stat.icon] + '</div>' +
      '<div class="sd-card__trend">' + icons.trendUp + ' ' + escapeHtml(stat.trend) + '</div>' +
      '</div>' +
      '<div class="sd-card__value">' + escapeHtml(stat.value) + '</div>' +
      '<div class="sd-card__label">' + escapeHtml(stat.label) + '</div>' +
      '</div>';
  });

  html += '</div></div>';
  container.innerHTML = html;
})();`;
  }
};

/**
 * Timeline Template
 * Vertical timeline for events or milestones
 */
const timelineTemplate: IJavaScriptTemplate = {
  id: 'timeline',
  name: 'Timeline',
  description: 'Vertical timeline for displaying events, milestones, or history',
  category: 'content',
  icon: '📅',
  configOptions: [
    { key: 'title', label: 'Timeline Title', type: 'text', default: 'Project Timeline', description: 'Main heading' },
    { key: 'primaryColor', label: 'Primary Color', type: 'color', default: '#8b5cf6', description: 'Accent color' },
    { key: 'backgroundColor', label: 'Background Color', type: 'color', default: '#1e1b4b', description: 'Page background' },
    { key: 'event1Date', label: 'Event 1 Date', type: 'text', default: 'January 2024', description: 'First event date' },
    { key: 'event1Title', label: 'Event 1 Title', type: 'text', default: 'Project Kickoff', description: 'First event title' },
    { key: 'event1Desc', label: 'Event 1 Description', type: 'text', default: 'Initial planning and team formation', description: 'First event description' },
    { key: 'event2Date', label: 'Event 2 Date', type: 'text', default: 'March 2024', description: 'Second event date' },
    { key: 'event2Title', label: 'Event 2 Title', type: 'text', default: 'Development Phase', description: 'Second event title' },
    { key: 'event2Desc', label: 'Event 2 Description', type: 'text', default: 'Core features implementation', description: 'Second event description' },
    { key: 'event3Date', label: 'Event 3 Date', type: 'text', default: 'June 2024', description: 'Third event date' },
    { key: 'event3Title', label: 'Event 3 Title', type: 'text', default: 'Beta Launch', description: 'Third event title' },
    { key: 'event3Desc', label: 'Event 3 Description', type: 'text', default: 'Public beta testing begins', description: 'Third event description' },
    { key: 'event4Date', label: 'Event 4 Date', type: 'text', default: 'September 2024', description: 'Fourth event date' },
    { key: 'event4Title', label: 'Event 4 Title', type: 'text', default: 'Official Release', description: 'Fourth event title' },
    { key: 'event4Desc', label: 'Event 4 Description', type: 'text', default: 'Version 1.0 goes live', description: 'Fourth event description' },
  ],
  generateCode: (config: IJavaScriptTemplateConfig) => {
    return `// Timeline Template - Generated by PiCanvas
(function() {
  const config = ${JSON.stringify(config, null, 2)};

  const events = [
    { date: config.event1Date || 'January 2024', title: config.event1Title || 'Project Kickoff', desc: config.event1Desc || 'Initial planning' },
    { date: config.event2Date || 'March 2024', title: config.event2Title || 'Development Phase', desc: config.event2Desc || 'Core features' },
    { date: config.event3Date || 'June 2024', title: config.event3Title || 'Beta Launch', desc: config.event3Desc || 'Public beta' },
    { date: config.event4Date || 'September 2024', title: config.event4Title || 'Official Release', desc: config.event4Desc || 'Version 1.0' }
  ];

  function escapeHtml(str) { return String(str).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;'); }

  let html = '<style>' +
    ':root { --tl-primary: ' + (config.primaryColor || '#8b5cf6') + '; --tl-bg: ' + (config.backgroundColor || '#1e1b4b') + '; }' +
    '.tl-container { font-family: "Segoe UI", -apple-system, sans-serif; background: var(--tl-bg); min-height: 100vh; padding: 60px 24px; }' +
    '.tl-inner { max-width: 800px; margin: 0 auto; }' +
    '.tl-title { color: #fff; font-size: 2.5rem; font-weight: 700; text-align: center; margin: 0 0 60px; }' +
    '.tl-timeline { position: relative; padding-left: 40px; }' +
    '.tl-timeline::before { content: ""; position: absolute; left: 12px; top: 0; bottom: 0; width: 2px; background: linear-gradient(to bottom, var(--tl-primary), rgba(139, 92, 246, 0.2)); }' +
    '.tl-event { position: relative; padding-bottom: 48px; opacity: 0; transform: translateX(-20px); animation: tlSlideIn 0.6s forwards; }' +
    '.tl-event:nth-child(1) { animation-delay: 0.1s; }' +
    '.tl-event:nth-child(2) { animation-delay: 0.2s; }' +
    '.tl-event:nth-child(3) { animation-delay: 0.3s; }' +
    '.tl-event:nth-child(4) { animation-delay: 0.4s; }' +
    '@keyframes tlSlideIn { to { opacity: 1; transform: translateX(0); } }' +
    '.tl-event__dot { position: absolute; left: -40px; top: 4px; width: 24px; height: 24px; background: var(--tl-primary); border-radius: 50%; border: 4px solid var(--tl-bg); box-shadow: 0 0 20px var(--tl-primary); }' +
    '.tl-event__date { color: var(--tl-primary); font-size: 0.9rem; font-weight: 600; margin-bottom: 8px; text-transform: uppercase; letter-spacing: 0.05em; }' +
    '.tl-event__card { background: rgba(255,255,255,0.05); border: 1px solid rgba(255,255,255,0.1); border-radius: 16px; padding: 24px; transition: all 0.3s; }' +
    '.tl-event__card:hover { transform: translateX(8px); border-color: var(--tl-primary); }' +
    '.tl-event__title { color: #fff; font-size: 1.25rem; font-weight: 600; margin: 0 0 8px; }' +
    '.tl-event__desc { color: rgba(255,255,255,0.7); line-height: 1.6; margin: 0; }' +
    '</style>';

  html += '<div class="tl-container"><div class="tl-inner">' +
    '<h1 class="tl-title">' + escapeHtml(config.title || 'Project Timeline') + '</h1>' +
    '<div class="tl-timeline">';

  events.forEach(function(event) {
    html += '<div class="tl-event">' +
      '<div class="tl-event__dot"></div>' +
      '<div class="tl-event__date">' + escapeHtml(event.date) + '</div>' +
      '<div class="tl-event__card">' +
      '<h3 class="tl-event__title">' + escapeHtml(event.title) + '</h3>' +
      '<p class="tl-event__desc">' + escapeHtml(event.desc) + '</p>' +
      '</div></div>';
  });

  html += '</div></div></div>';
  container.innerHTML = html;
})();`;
  }
};

/**
 * Card Grid Template
 * Responsive grid of content cards
 */
const cardGridTemplate: IJavaScriptTemplate = {
  id: 'card-grid',
  name: 'Card Grid',
  description: 'Responsive grid layout for displaying content cards',
  category: 'layout',
  icon: '🎴',
  configOptions: [
    { key: 'title', label: 'Section Title', type: 'text', default: 'Our Services', description: 'Main heading' },
    { key: 'subtitle', label: 'Section Subtitle', type: 'text', default: 'What we offer', description: 'Subheading' },
    { key: 'primaryColor', label: 'Primary Color', type: 'color', default: '#f59e0b', description: 'Accent color' },
    { key: 'backgroundColor', label: 'Background Color', type: 'color', default: '#18181b', description: 'Page background' },
    { key: 'columns', label: 'Columns', type: 'dropdown', default: '3', options: [{ key: '2', text: '2 Columns' }, { key: '3', text: '3 Columns' }, { key: '4', text: '4 Columns' }], description: 'Number of columns' },
    { key: 'card1Title', label: 'Card 1 Title', type: 'text', default: 'Consulting', description: 'First card title' },
    { key: 'card1Desc', label: 'Card 1 Description', type: 'text', default: 'Expert guidance for your business needs', description: 'First card description' },
    { key: 'card2Title', label: 'Card 2 Title', type: 'text', default: 'Development', description: 'Second card title' },
    { key: 'card2Desc', label: 'Card 2 Description', type: 'text', default: 'Custom software solutions built for you', description: 'Second card description' },
    { key: 'card3Title', label: 'Card 3 Title', type: 'text', default: 'Design', description: 'Third card title' },
    { key: 'card3Desc', label: 'Card 3 Description', type: 'text', default: 'Beautiful interfaces that users love', description: 'Third card description' },
    { key: 'card4Title', label: 'Card 4 Title', type: 'text', default: 'Support', description: 'Fourth card title' },
    { key: 'card4Desc', label: 'Card 4 Description', type: 'text', default: '24/7 assistance when you need it', description: 'Fourth card description' },
    { key: 'card5Title', label: 'Card 5 Title', type: 'text', default: 'Training', description: 'Fifth card title' },
    { key: 'card5Desc', label: 'Card 5 Description', type: 'text', default: 'Empower your team with knowledge', description: 'Fifth card description' },
    { key: 'card6Title', label: 'Card 6 Title', type: 'text', default: 'Analytics', description: 'Sixth card title' },
    { key: 'card6Desc', label: 'Card 6 Description', type: 'text', default: 'Data-driven insights for growth', description: 'Sixth card description' },
  ],
  generateCode: (config: IJavaScriptTemplateConfig) => {
    return `// Card Grid Template - Generated by PiCanvas
(function() {
  const config = ${JSON.stringify(config, null, 2)};

  const icons = {
    consulting: '<svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><circle cx="12" cy="12" r="10"/><path d="M9.09 9a3 3 0 0 1 5.83 1c0 2-3 3-3 3"/><line x1="12" y1="17" x2="12.01" y2="17"/></svg>',
    development: '<svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><polyline points="16 18 22 12 16 6"/><polyline points="8 6 2 12 8 18"/></svg>',
    design: '<svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><circle cx="13.5" cy="6.5" r=".5"/><circle cx="17.5" cy="10.5" r=".5"/><circle cx="8.5" cy="7.5" r=".5"/><circle cx="6.5" cy="12.5" r=".5"/><path d="M12 2C6.5 2 2 6.5 2 12s4.5 10 10 10c.926 0 1.648-.746 1.648-1.688 0-.437-.18-.835-.437-1.125-.29-.289-.438-.652-.438-1.125a1.64 1.64 0 0 1 1.668-1.668h1.996c3.051 0 5.555-2.503 5.555-5.555C21.965 6.012 17.461 2 12 2z"/></svg>',
    support: '<svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M18 18.72a9.094 9.094 0 0 0 3.741-.479 3 3 0 0 0-4.682-2.72m.94 3.198.001.031c0 .225-.012.447-.037.666A11.944 11.944 0 0 1 12 21c-2.17 0-4.207-.576-5.963-1.584A6.062 6.062 0 0 1 6 18.719m12 0a5.971 5.971 0 0 0-.941-3.197m0 0A5.995 5.995 0 0 0 12 12.75a5.995 5.995 0 0 0-5.058 2.772m0 0a3 3 0 0 0-4.681 2.72 8.986 8.986 0 0 0 3.74.477m.94-3.197a5.971 5.971 0 0 0-.94 3.197M15 6.75a3 3 0 1 1-6 0 3 3 0 0 1 6 0Zm6 3a2.25 2.25 0 1 1-4.5 0 2.25 2.25 0 0 1 4.5 0Zm-13.5 0a2.25 2.25 0 1 1-4.5 0 2.25 2.25 0 0 1 4.5 0Z"/></svg>',
    training: '<svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M22 10v6M2 10l10-5 10 5-10 5z"/><path d="M6 12v5c3 3 9 3 12 0v-5"/></svg>',
    analytics: '<svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><line x1="18" y1="20" x2="18" y2="10"/><line x1="12" y1="20" x2="12" y2="4"/><line x1="6" y1="20" x2="6" y2="14"/></svg>'
  };

  const cards = [
    { title: config.card1Title || 'Consulting', desc: config.card1Desc || 'Expert guidance', icon: 'consulting' },
    { title: config.card2Title || 'Development', desc: config.card2Desc || 'Custom solutions', icon: 'development' },
    { title: config.card3Title || 'Design', desc: config.card3Desc || 'Beautiful interfaces', icon: 'design' },
    { title: config.card4Title || 'Support', desc: config.card4Desc || '24/7 assistance', icon: 'support' },
    { title: config.card5Title || 'Training', desc: config.card5Desc || 'Team empowerment', icon: 'training' },
    { title: config.card6Title || 'Analytics', desc: config.card6Desc || 'Data insights', icon: 'analytics' }
  ];

  const columns = config.columns || '3';
  const minWidth = columns === '2' ? '400px' : columns === '4' ? '240px' : '300px';

  function escapeHtml(str) { return String(str).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;'); }

  let html = '<style>' +
    ':root { --cg-primary: ' + (config.primaryColor || '#f59e0b') + '; --cg-bg: ' + (config.backgroundColor || '#18181b') + '; }' +
    '.cg-container { font-family: "Segoe UI", -apple-system, sans-serif; background: var(--cg-bg); min-height: 100vh; padding: 80px 24px; }' +
    '.cg-inner { max-width: 1200px; margin: 0 auto; }' +
    '.cg-header { text-align: center; margin-bottom: 60px; }' +
    '.cg-subtitle { color: var(--cg-primary); font-size: 0.9rem; font-weight: 600; text-transform: uppercase; letter-spacing: 0.1em; margin: 0 0 12px; }' +
    '.cg-title { color: #fff; font-size: 2.5rem; font-weight: 700; margin: 0; }' +
    '.cg-grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(' + minWidth + ', 1fr)); gap: 24px; }' +
    '.cg-card { background: rgba(255,255,255,0.03); border: 1px solid rgba(255,255,255,0.08); border-radius: 20px; padding: 32px; text-align: center; transition: all 0.3s; opacity: 0; transform: translateY(20px); animation: cgFadeIn 0.6s forwards; }' +
    '.cg-card:nth-child(1) { animation-delay: 0.1s; }' +
    '.cg-card:nth-child(2) { animation-delay: 0.15s; }' +
    '.cg-card:nth-child(3) { animation-delay: 0.2s; }' +
    '.cg-card:nth-child(4) { animation-delay: 0.25s; }' +
    '.cg-card:nth-child(5) { animation-delay: 0.3s; }' +
    '.cg-card:nth-child(6) { animation-delay: 0.35s; }' +
    '@keyframes cgFadeIn { to { opacity: 1; transform: translateY(0); } }' +
    '.cg-card:hover { transform: translateY(-8px); border-color: var(--cg-primary); box-shadow: 0 20px 40px rgba(0,0,0,0.3), 0 0 40px rgba(245, 158, 11, 0.1); }' +
    '.cg-card__icon { width: 72px; height: 72px; background: linear-gradient(135deg, var(--cg-primary), rgba(245, 158, 11, 0.3)); border-radius: 20px; display: flex; align-items: center; justify-content: center; margin: 0 auto 24px; color: #fff; }' +
    '.cg-card__title { color: #fff; font-size: 1.25rem; font-weight: 600; margin: 0 0 12px; }' +
    '.cg-card__desc { color: rgba(255,255,255,0.6); line-height: 1.6; margin: 0; }' +
    '</style>';

  html += '<div class="cg-container"><div class="cg-inner">' +
    '<div class="cg-header">' +
    '<p class="cg-subtitle">' + escapeHtml(config.subtitle || 'What we offer') + '</p>' +
    '<h1 class="cg-title">' + escapeHtml(config.title || 'Our Services') + '</h1>' +
    '</div>' +
    '<div class="cg-grid">';

  cards.forEach(function(card) {
    html += '<div class="cg-card">' +
      '<div class="cg-card__icon">' + icons[card.icon] + '</div>' +
      '<h3 class="cg-card__title">' + escapeHtml(card.title) + '</h3>' +
      '<p class="cg-card__desc">' + escapeHtml(card.desc) + '</p>' +
      '</div>';
  });

  html += '</div></div></div>';
  container.innerHTML = html;
})();`;
  }
};

/**
 * Hero Section Template
 * Simple hero section with title, description, and buttons
 */
const heroSectionTemplate: IJavaScriptTemplate = {
  id: 'hero-section',
  name: 'Hero Section',
  description: 'Simple hero section with title, description, and call-to-action',
  category: 'landing',
  icon: '🌟',
  configOptions: [
    { key: 'title', label: 'Hero Title', type: 'text', default: 'Welcome to Our Platform', description: 'Main heading' },
    { key: 'titleHighlight', label: 'Title Highlight', type: 'text', default: 'Platform', description: 'Word to highlight with gradient' },
    { key: 'description', label: 'Description', type: 'textarea', default: 'Build amazing experiences with our powerful tools and services. Start your journey today.', description: 'Hero description' },
    { key: 'primaryButtonText', label: 'Primary Button', type: 'text', default: 'Get Started', description: 'Primary button text' },
    { key: 'secondaryButtonText', label: 'Secondary Button', type: 'text', default: 'Learn More', description: 'Secondary button text' },
    { key: 'primaryColor', label: 'Primary Color', type: 'color', default: '#06b6d4', description: 'Accent color' },
    { key: 'backgroundColor', label: 'Background Color', type: 'color', default: '#0c0a09', description: 'Page background' },
    { key: 'showBadge', label: 'Show Badge', type: 'toggle', default: true, description: 'Show announcement badge' },
    { key: 'badgeText', label: 'Badge Text', type: 'text', default: 'New: Version 2.0 Released', description: 'Badge announcement text' },
    { key: 'minHeight', label: 'Minimum Height', type: 'dropdown', default: '100vh', options: [{ key: '50vh', text: '50% Viewport' }, { key: '75vh', text: '75% Viewport' }, { key: '100vh', text: 'Full Viewport' }], description: 'Section height' },
  ],
  generateCode: (config: IJavaScriptTemplateConfig) => {
    return `// Hero Section Template - Generated by PiCanvas
(function() {
  const config = ${JSON.stringify(config, null, 2)};

  function escapeHtml(str) { return String(str).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;'); }

  // Highlight the specified word in the title
  const title = config.title || 'Welcome to Our Platform';
  const highlight = config.titleHighlight || 'Platform';
  const titleHtml = title.replace(new RegExp('(' + highlight.replace(/[.*+?^\${}()|[\\]\\\\]/g, '\\\\$&') + ')', 'gi'), '<span class="hs-title__highlight">$1</span>');

  let html = '<style>' +
    ':root { --hs-primary: ' + (config.primaryColor || '#06b6d4') + '; --hs-bg: ' + (config.backgroundColor || '#0c0a09') + '; }' +
    '.hs-container { font-family: "Segoe UI", -apple-system, sans-serif; background: var(--hs-bg); min-height: ' + (config.minHeight || '100vh') + '; display: flex; flex-direction: column; align-items: center; justify-content: center; text-align: center; padding: 60px 24px; position: relative; overflow: hidden; }' +
    '.hs-background { position: absolute; inset: 0; z-index: 0; }' +
    '.hs-glow { position: absolute; width: 600px; height: 600px; border-radius: 50%; filter: blur(100px); opacity: 0.3; }' +
    '.hs-glow--1 { background: var(--hs-primary); top: -200px; left: 50%; transform: translateX(-50%); }' +
    '.hs-glow--2 { background: #8b5cf6; bottom: -200px; right: -100px; }' +
    '.hs-content { position: relative; z-index: 1; max-width: 800px; }' +
    '.hs-badge { display: inline-flex; align-items: center; gap: 8px; padding: 8px 16px; background: rgba(255,255,255,0.1); border: 1px solid rgba(255,255,255,0.1); border-radius: 100px; font-size: 0.875rem; color: rgba(255,255,255,0.9); margin-bottom: 32px; backdrop-filter: blur(8px); animation: hsFadeIn 0.6s forwards; }' +
    '.hs-badge__dot { width: 8px; height: 8px; background: var(--hs-primary); border-radius: 50%; animation: hsPulse 2s infinite; }' +
    '@keyframes hsPulse { 0%, 100% { opacity: 1; } 50% { opacity: 0.5; } }' +
    '.hs-title { font-size: clamp(2.5rem, 6vw, 4rem); font-weight: 700; color: #fff; line-height: 1.1; margin: 0 0 24px; opacity: 0; animation: hsFadeIn 0.6s 0.1s forwards; }' +
    '.hs-title__highlight { background: linear-gradient(135deg, var(--hs-primary), #a855f7); -webkit-background-clip: text; -webkit-text-fill-color: transparent; background-clip: text; }' +
    '.hs-description { font-size: 1.25rem; color: rgba(255,255,255,0.7); line-height: 1.6; margin: 0 0 40px; opacity: 0; animation: hsFadeIn 0.6s 0.2s forwards; }' +
    '.hs-buttons { display: flex; gap: 16px; justify-content: center; flex-wrap: wrap; opacity: 0; animation: hsFadeIn 0.6s 0.3s forwards; }' +
    '@keyframes hsFadeIn { to { opacity: 1; } }' +
    '.hs-btn { padding: 16px 32px; border-radius: 12px; font-size: 1rem; font-weight: 600; cursor: pointer; transition: all 0.2s; border: none; }' +
    '.hs-btn--primary { background: linear-gradient(135deg, var(--hs-primary), #0891b2); color: #fff; box-shadow: 0 4px 20px rgba(6, 182, 212, 0.4); }' +
    '.hs-btn--primary:hover { transform: translateY(-2px); box-shadow: 0 8px 30px rgba(6, 182, 212, 0.5); }' +
    '.hs-btn--secondary { background: transparent; color: #fff; border: 2px solid rgba(255,255,255,0.2); }' +
    '.hs-btn--secondary:hover { border-color: rgba(255,255,255,0.4); background: rgba(255,255,255,0.05); }' +
    '</style>';

  html += '<div class="hs-container">' +
    '<div class="hs-background"><div class="hs-glow hs-glow--1"></div><div class="hs-glow hs-glow--2"></div></div>' +
    '<div class="hs-content">';

  if (config.showBadge !== false) {
    html += '<div class="hs-badge"><span class="hs-badge__dot"></span>' + escapeHtml(config.badgeText || 'New: Version 2.0 Released') + '</div>';
  }

  html += '<h1 class="hs-title">' + titleHtml + '</h1>' +
    '<p class="hs-description">' + escapeHtml(config.description || 'Build amazing experiences with our powerful tools.') + '</p>' +
    '<div class="hs-buttons">' +
    '<button class="hs-btn hs-btn--primary">' + escapeHtml(config.primaryButtonText || 'Get Started') + '</button>' +
    '<button class="hs-btn hs-btn--secondary">' + escapeHtml(config.secondaryButtonText || 'Learn More') + '</button>' +
    '</div>' +
    '</div></div>';

  container.innerHTML = html;
})();`;
  }
};

// ============================================================================
// Export Templates
// ============================================================================

export const JavaScriptTemplates: IJavaScriptTemplate[] = [
  landingPageTemplate,
  statsDashboardTemplate,
  timelineTemplate,
  cardGridTemplate,
  heroSectionTemplate
];

/**
 * Get a template by ID
 */
export function getJavaScriptTemplate(templateId: string): IJavaScriptTemplate | undefined {
  return JavaScriptTemplates.find(t => t.id === templateId);
}

/**
 * Get template dropdown options for property pane
 */
export function getJavaScriptTemplateOptions(): { key: string; text: string }[] {
  return [
    { key: '', text: '— None (Custom Code) —' },
    ...JavaScriptTemplates.map(t => ({
      key: t.id,
      text: `${t.icon} ${t.name}`
    }))
  ];
}
